insert into Actor (PosRating,NegRating,Name,Surname,Description) values (0,0,'Mika2','S','description2')
insert into Actor (PosRating,NegRating,Name,Surname,Description) values (0,0,'Mika3','O','description3')
insert into Actor (PosRating,NegRating,Name,Surname,Description) values (0,0,'Mika4','L','description4')
insert into Actor (PosRating,NegRating,Name,Surname,Description) values (0,0,'Mika5','B','description5')

insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (1,1)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (1,2)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (1,4)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (2,1)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (2,2)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (3,1)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (3,2)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (3,3)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (3,5)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (4,5)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (5,1)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (5,5)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (6,5)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (7,5)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (8,1)
insert into FilmsAFilmsActorsMod(FilmID,ActorID) values (8,3)